// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vms/v1alpha1/workloadentry.proto

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for WorkloadEntry
func (this *WorkloadEntry) MarshalJSON() ([]byte, error) {
	str, err := WorkloadentryMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WorkloadEntry
func (this *WorkloadEntry) UnmarshalJSON(b []byte) error {
	return WorkloadentryUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Endpoint
func (this *Endpoint) MarshalJSON() ([]byte, error) {
	str, err := WorkloadentryMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Endpoint
func (this *Endpoint) UnmarshalJSON(b []byte) error {
	return WorkloadentryUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	WorkloadentryMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	WorkloadentryUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
