# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vms/v1alpha1/workloadentry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vms/v1alpha1/workloadentry.proto',
  package='istio.vms.v1alpha1',
  syntax='proto3',
  serialized_options=_b('Z\031istio.io/api/vms/v1alpha1'),
  serialized_pb=_b('\n vms/v1alpha1/workloadentry.proto\x12\x12istio.vms.v1alpha1\"^\n\rWorkloadEntry\x12\x1c\n\x14service_account_name\x18\x01 \x01(\t\x12/\n\tendpoints\x18\x02 \x03(\x0b\x32\x1c.istio.vms.v1alpha1.Endpoint\"\x1d\n\x08\x45ndpoint\x12\x11\n\taddresses\x18\x01 \x03(\tB\x1bZ\x19istio.io/api/vms/v1alpha1b\x06proto3')
)




_WORKLOADENTRY = _descriptor.Descriptor(
  name='WorkloadEntry',
  full_name='istio.vms.v1alpha1.WorkloadEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_account_name', full_name='istio.vms.v1alpha1.WorkloadEntry.service_account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endpoints', full_name='istio.vms.v1alpha1.WorkloadEntry.endpoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=150,
)


_ENDPOINT = _descriptor.Descriptor(
  name='Endpoint',
  full_name='istio.vms.v1alpha1.Endpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='istio.vms.v1alpha1.Endpoint.addresses', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=181,
)

_WORKLOADENTRY.fields_by_name['endpoints'].message_type = _ENDPOINT
DESCRIPTOR.message_types_by_name['WorkloadEntry'] = _WORKLOADENTRY
DESCRIPTOR.message_types_by_name['Endpoint'] = _ENDPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkloadEntry = _reflection.GeneratedProtocolMessageType('WorkloadEntry', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOADENTRY,
  '__module__' : 'vms.v1alpha1.workloadentry_pb2'
  # @@protoc_insertion_point(class_scope:istio.vms.v1alpha1.WorkloadEntry)
  })
_sym_db.RegisterMessage(WorkloadEntry)

Endpoint = _reflection.GeneratedProtocolMessageType('Endpoint', (_message.Message,), {
  'DESCRIPTOR' : _ENDPOINT,
  '__module__' : 'vms.v1alpha1.workloadentry_pb2'
  # @@protoc_insertion_point(class_scope:istio.vms.v1alpha1.Endpoint)
  })
_sym_db.RegisterMessage(Endpoint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
